spring:
  data:
    mongodb:
      host: ovh.klimas7.pl
      username: admin
      password: k7admin
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        data: debug
        mongodb:
          core:
            MongoTemplate: trace